# Generated by Django 4.2.6 on 2024-08-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=200, verbose_name='料理タイトル')),
                ('recipe_image', models.ImageField(upload_to='recipes/', verbose_name='料理写真')),
                ('vote', models.IntegerField(default=0, verbose_name='閲覧回数')),
                ('detail_text', models.TextField(max_length=200, verbose_name='料理説明')),
                ('genre', models.CharField(choices=[('main', '主菜'), ('side', '副菜'), ('course', '主食'), ('dessert', '菓子')], max_length=10, verbose_name='ジャンル')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='ステップ番号')),
                ('step_text', models.CharField(max_length=300, verbose_name='作り方文章')),
                ('step_image', models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name='作り方の写真')),
                ('step_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='作り方の動画')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, verbose_name='材料名')),
                ('amount', models.CharField(max_length=100, verbose_name='分量')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='app.recipe', verbose_name='class Recipeを継承')),
            ],
        ),
    ]
