# Generated by Django 4.2.6 on 2024-08-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_title', models.CharField(max_length=200)),
                ('cooking_images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=300)),
                ('steps_text', models.CharField(max_length=300)),
                ('steps_images', models.ImageField(upload_to='')),
                ('detail_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('cooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cooking')),
            ],
        ),
    ]
