# Generated by Django 4.2.6 on 2024-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='icon',
            new_name='user_icon',
        ),
    ]
