# Generated by Django 4.2.6 on 2024-08-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_title', models.CharField(max_length=200)),
                ('cooking_images', models.ImageField(upload_to='recipes/')),
                ('votes', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('detail_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('steps_text', models.CharField(max_length=300)),
                ('steps_images', models.ImageField(blank=True, null=True, upload_to='steps/')),
                ('steps_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='cooking',
        ),
        migrations.DeleteModel(
            name='Cooking',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='app.recipe'),
        ),
    ]
