# Generated by Django 4.2.6 on 2024-10-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_icon_customuser_user_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_name', models.CharField(max_length=50, verbose_name='アレルギー')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergy',
            field=models.CharField(default='なし', max_length=1000),
        ),
    ]
