# Generated by Django 4.2.6 on 2024-11-18 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_icon_customuser_user_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventorylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=120, verbose_name='食材名')),
                ('expiration_date', models.DateField(verbose_name='賞味期限')),
                ('storage_method', models.CharField(default='未設定', max_length=100, verbose_name='保存方法')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
