# Generated by Django 5.1 on 2024-09-07 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_recipe_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=200)),
                ('review', models.CharField(choices=[('one', '★'), ('two', '★★'), ('three', '★★★'), ('four', '★★★★'), ('five', '★★★★★')], max_length=10, verbose_name='レビュー')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.recipe')),
            ],
        ),
    ]
