# Generated by Django 4.2.6 on 2024-08-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ingredient_recipe_step_remove_detail_cooking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_images',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_title',
            new_name='recipe_title',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='votes',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='steps_images',
            new_name='step_image',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='steps_text',
            new_name='step_text',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='steps_video',
            new_name='step_video',
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='app.recipe'),
        ),
    ]
