# Generated by Django 4.2.6 on 2024-08-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_cooking_images_recipe_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='分量'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='material',
            field=models.CharField(max_length=100, verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='detail_text',
            field=models.TextField(max_length=200, verbose_name='料理説明'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='recipes/', verbose_name='料理写真'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(max_length=200, verbose_name='料理タイトル'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='閲覧回数'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name='作り方の写真'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.PositiveIntegerField(verbose_name='ステップ番号'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_text',
            field=models.CharField(max_length=300, verbose_name='作り方文章'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='作り方の動画'),
        ),
    ]
