# Generated by Django 5.0.7 on 2024-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_content_comment_parent_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=3),
        ),
    ]
