# Generated by Django 5.0.7 on 2024-11-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
    ]
